using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Flurl.Http;

namespace Arcus.EventGrid.Publishing
{
    /// <summary>
    /// Event Grid publisher can be used to publish events to a custom Event Grid topic
    /// </summary>
    public class EventGridPublisher
    {
        /// <summary>
        /// Endpoint url of the Event Grid topic
        /// </summary>
        private string TopicEndpoint { get; set; }

        /// <summary>
        /// Secret Authorization Key for the Event Grid topic
        /// </summary>
        private string AuthorizationKey { get; set; }

        /// <summary>
        /// Creates a validated EventGrid publisher
        /// </summary>
        /// <param name="topicEndpoint">Endpoint url of the Event Grid topic</param>
        /// <param name="authorizationKey">Secret Authorization Key for the Event Grid topic</param>
        /// <returns></returns>
        public static EventGridPublisher Create(string topicEndpoint, string authorizationKey)
        {
            //TODO: should be replaced by Guard package call
            Guard.AgainstNullOrEmptyValue(topicEndpoint, nameof(topicEndpoint), "The topic endpoint must not be empty and is required");
            Guard.AgainstNullOrEmptyValue(authorizationKey, nameof(authorizationKey), "The authorization key must not be empty and is required");
            return new EventGridPublisher
            {
                TopicEndpoint = topicEndpoint,
                AuthorizationKey = authorizationKey
            };
        }

        /// <summary>
        /// Publish an event grid message to the configured Event Grid topic
        /// </summary>
        /// <typeparam name="T">Type of the specific EventData</typeparam>
        /// <param name="subject">Subject</param>
        /// <param name="eventType">Event Type</param>
        /// <param name="data">Typed event data</param>
        /// <param name="id">Unique id of the event, generated by default</param>
        /// <returns></returns>
        public async Task Publish<T>(string subject, string eventType, IEnumerable<T> data, string id = null) where T : class
        {
            var eventList = data.Select(eventData => new Event<T>
            {
                Subject = subject,
                EventType = eventType,
                EventTime = DateTime.UtcNow,
                Id = id ?? Guid.NewGuid().ToString(),
                Data = eventData
            }).ToList();

            // Calling HTTP endpoint
            var response = await TopicEndpoint
                .WithHeader("aeg-sas-key", AuthorizationKey)
                .PostJsonAsync(eventList);

            if (!response.IsSuccessStatusCode)
            {
                // Throw custom exception in case of failure 
                throw new ApplicationException($"Event grid publishing failed with status {response.StatusCode} and content {await response.Content.ReadAsStringAsync()}");
            }
        }
    }
}
